export const GET_ITEMS = 'GET_ITEMS';
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const GET_COMMONITEMS = 'GET_COMMONITEMS';
export const ADD_COMMONITEM = 'ADD_COMMONITEM';
export const COMMONITEMS_LOADING = 'COMMONITEMS_LOADING';